// Mocks generated by Mockito 5.4.5 from annotations
// in sofomo_task/test/modules/repositories_list/bloc/repositories_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_bloc/flutter_bloc.dart' as _i6;
import 'package:github_repository/github_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:sofomo_task/modules/repositories_list/bloc/search_cubit.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRepositoriesResponse_0 extends _i1.SmartFake
    implements _i2.RepositoriesResponse {
  _FakeRepositoriesResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GithubRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGithubRepository extends _i1.Mock implements _i2.GithubRepository {
  MockGithubRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.RepositoriesResponse> getRepositories({
    required String? query,
    required int? page,
    required int? resultsPerPage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRepositories, [], {
              #query: query,
              #page: page,
              #resultsPerPage: resultsPerPage,
            }),
            returnValue: _i3.Future<_i2.RepositoriesResponse>.value(
              _FakeRepositoriesResponse_0(
                this,
                Invocation.method(#getRepositories, [], {
                  #query: query,
                  #page: page,
                  #resultsPerPage: resultsPerPage,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.RepositoriesResponse>);

  @override
  _i3.Future<List<_i2.Issue>> getIssues({
    required String? owner,
    required String? repository,
    required int? page,
    required int? resultsPerPage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getIssues, [], {
              #owner: owner,
              #repository: repository,
              #page: page,
              #resultsPerPage: resultsPerPage,
            }),
            returnValue: _i3.Future<List<_i2.Issue>>.value(<_i2.Issue>[]),
          )
          as _i3.Future<List<_i2.Issue>>);

  @override
  _i3.Future<List<_i2.PullRequest>> getPullRequests({
    required String? owner,
    required String? repository,
    required int? page,
    required int? resultsPerPage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPullRequests, [], {
              #owner: owner,
              #repository: repository,
              #page: page,
              #resultsPerPage: resultsPerPage,
            }),
            returnValue: _i3.Future<List<_i2.PullRequest>>.value(
              <_i2.PullRequest>[],
            ),
          )
          as _i3.Future<List<_i2.PullRequest>>);
}

/// A class which mocks [SearchCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchCubit extends _i1.Mock implements _i4.SearchCubit {
  MockSearchCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#state),
            ),
          )
          as String);

  @override
  _i3.Stream<String> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i3.Stream<String>.empty(),
          )
          as _i3.Stream<String>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void search(String? query) => super.noSuchMethod(
    Invocation.method(#search, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(String? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i6.Change<String>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
